'use strict';

// Catalogul de televiziuni românești.
// Format: [slug, nume, categorie, paginaOficiala]
// Fluxul se configureaza prin variabila de mediu RAULTV_<SLUG>_URL (vezi README).

const CATALOG = [
  // ---------- Generaliste ----------
  ['prima-tv', 'Prima TV', 'Generaliste', 'https://www.primatv.ro/'],
  ['pro-tv', 'PRO TV', 'Generaliste', 'https://www.protv.ro/'],
  ['antena-1', 'Antena 1', 'Generaliste', 'https://a1.ro/'],
  ['kanal-d', 'Kanal D', 'Generaliste', 'https://www.kanald.ro/live.html'],
  ['kanal-d2', 'Kanal D2', 'Generaliste', 'https://www.kanald2.ro/'],
  ['tvr-1', 'TVR 1', 'Generaliste', 'https://www.tvrplus.ro/'],
  ['tvr-2', 'TVR 2', 'Generaliste', 'https://www.tvrplus.ro/'],
  ['tvr-3', 'TVR 3', 'Generaliste', 'https://www.tvrplus.ro/'],
  ['tvr-international', 'TVR Internațional', 'Generaliste', 'https://www.tvrplus.ro/'],
  ['tvr-moldova', 'TVR Moldova', 'Generaliste', 'https://tvrmoldova.md/live'],
  ['acasa-tv', 'Acasă TV', 'Generaliste', 'https://acasatv.protv.ro/'],
  ['antena-stars', 'Antena Stars', 'Generaliste', 'https://antenastars.ro/'],
  ['national-tv', 'Național TV', 'Generaliste', 'https://www.nationaltv.ro/'],
  ['n24-plus', 'N24 Plus', 'Generaliste', 'https://www.nationaltv.ro/'],
  ['metropola-tv', 'Metropola TV', 'Generaliste', 'https://www.metropolatv.ro/'],
  ['sens-tv', 'SENS TV', 'Generaliste', 'https://www.senstv.ro/'],
  ['telestar-1', 'Telestar 1', 'Generaliste', 'https://telestar1.ro/'],
  ['a7-tv', 'A7 TV', 'Generaliste', 'https://a7tv.ro/'],
  ['kapital-tv', 'Kapital TV', 'Generaliste', 'https://kapitaltv.ro/'],
  ['h2-0-tv', 'H2.0 TV', 'Generaliste', 'https://h20tv.ro/'],
  ['est-tv', 'Est TV', 'Generaliste', 'https://esttv.ro/'],
  ['prima-plus', 'Prima Plus', 'Generaliste', 'https://www.primatv.ro/'],

  // ---------- Știri ----------
  ['digi-24', 'Digi 24', 'Știri', 'https://www.digi24.ro/live/digi24'],
  ['antena-3-cnn', 'Antena 3 CNN', 'Știri', 'https://www.antena3.ro/live'],
  ['b1-tv', 'B1 TV', 'Știri', 'https://www.b1tv.ro/live'],
  ['realitatea-plus', 'Realitatea Plus', 'Știri', 'https://www.realitatea.net/live'],
  ['romania-tv', 'România TV', 'Știri', 'https://www.romaniatv.net/live'],
  ['euronews-romania', 'Euronews România', 'Știri', 'https://www.euronews.ro/live'],
  ['aleph-news', 'Aleph News', 'Știri', 'https://alephnews.ro/'],
  ['prima-news', 'Prima News', 'Știri', 'https://primanews.ro/'],
  ['tvr-info', 'TVR Info', 'Știri', 'https://www.tvrinfo.ro/'],
  ['profit-news-tv', 'Profit News TV', 'Știri', 'https://www.profit.ro/'],
  ['nasul-tv', 'Nașul TV', 'Știri', 'https://www.nasul.tv/'],
  ['republika-news', 'Republika News', 'Știri', 'https://republikanews.ro/'],
  ['b1-plus', 'B1 Plus', 'Știri', 'https://www.b1tv.ro/'],
  ['gold-fm-tv', 'Gold FM TV', 'Știri', 'https://goldfm.ro/'],

  // ---------- Sport ----------
  ['digi-sport-1', 'Digi Sport 1', 'Sport', 'https://www.digionline.ro/sport/digisport-1'],
  ['digi-sport-2', 'Digi Sport 2', 'Sport', 'https://www.digionline.ro/sport/digisport-2'],
  ['digi-sport-3', 'Digi Sport 3', 'Sport', 'https://www.digionline.ro/sport'],
  ['digi-sport-4', 'Digi Sport 4', 'Sport', 'https://www.digionline.ro/sport'],
  ['prima-sport-1', 'Prima Sport 1', 'Sport', 'https://www.primasport.ro/'],
  ['prima-sport-2', 'Prima Sport 2', 'Sport', 'https://www.primasport.ro/'],
  ['prima-sport-3', 'Prima Sport 3', 'Sport', 'https://www.primasport.ro/'],
  ['prima-sport-4', 'Prima Sport 4', 'Sport', 'https://www.primasport.ro/'],
  ['prima-sport-5', 'Prima Sport 5', 'Sport', 'https://www.primasport.ro/'],
  ['look-sport', 'Look Sport', 'Sport', 'https://www.primasport.ro/'],
  ['orange-sport-1', 'Orange Sport 1', 'Sport', 'https://www.orangesport.ro/'],
  ['orange-sport-2', 'Orange Sport 2', 'Sport', 'https://www.orangesport.ro/'],
  ['orange-sport-3', 'Orange Sport 3', 'Sport', 'https://www.orangesport.ro/'],
  ['orange-sport-4', 'Orange Sport 4', 'Sport', 'https://www.orangesport.ro/'],
  ['pro-arena', 'PRO Arena', 'Sport', 'https://www.protv.ro/'],
  ['tvr-sport', 'TVR Sport', 'Sport', 'https://www.tvrplus.ro/'],

  // ---------- Filme și seriale ----------
  ['pro-cinema', 'PRO Cinema', 'Filme', 'https://www.protv.ro/'],
  ['acasa-gold', 'Acasă Gold', 'Filme', 'https://acasatv.protv.ro/'],
  ['happy-channel', 'Happy Channel', 'Filme', 'https://happychannel.ro/'],
  ['film-now', 'Film Now', 'Filme', 'https://www.protv.ro/'],
  ['cinemaraton', 'Cinemaraton', 'Filme', 'https://cinemaronline.ro/'],
  ['nostalgia-tv', 'Nostalgia TV', 'Filme', 'https://www.clever-media.ro/'],
  ['bollywood-tv', 'Bollywood TV', 'Filme', 'https://bollywoodtv.ro/'],
  ['film-cafe', 'Film Cafe', 'Filme', 'https://filmcafe.ro/'],

  // ---------- Divertisment ----------
  ['comedy-est', 'ComedyEst', 'Divertisment', 'https://www.clever-media.ro/'],
  ['prima-comedy', 'Prima Comedy', 'Divertisment', 'https://www.primatv.ro/'],
  ['antena-comedy', 'Antena Comedy', 'Divertisment', 'https://a1.ro/'],
  ['happy-tv', 'Happy TV', 'Divertisment', 'https://happytv.ro/'],
  ['zaiafet-tv', 'Zaiafet TV', 'Divertisment', 'https://zaiafet.tv/'],

  // ---------- Documentare ----------
  ['digi-world', 'Digi World', 'Documentare', 'https://www.digionline.ro/'],
  ['digi-animal-world', 'Digi Animal World', 'Documentare', 'https://www.digionline.ro/'],
  ['prima-history', 'Prima History', 'Documentare', 'https://www.primatv.ro/'],
  ['travel-mix', 'Travel Mix', 'Documentare', 'https://travelmix.ro/'],
  ['exploris', 'Exploris', 'Documentare', 'https://www.clever-media.ro/'],
  ['history-tv', 'History Channel România', 'Documentare', 'https://www.history.ro/'],
  ['descopera-tv', 'Descoperă TV', 'Documentare', 'https://descoperatv.ro/'],

  // ---------- Lifestyle ----------
  ['digi-life', 'Digi Life', 'Lifestyle', 'https://www.digionline.ro/'],
  ['paprika-tv', 'Paprika TV', 'Lifestyle', 'https://paprikatv.ro/'],
  ['tlc-romania', 'TLC România', 'Lifestyle', 'https://www.tlc.ro/'],
  ['casa-si-gradina', 'Casa și Grădina TV', 'Lifestyle', 'https://casasigradina.tv/'],

  // ---------- Muzică ----------
  ['zu-tv', 'ZU TV', 'Muzică', 'https://zutv.ro/'],
  ['music-channel', 'Music Channel', 'Muzică', 'https://www.music-channel.ro/'],
  ['utv', 'U TV', 'Muzică', 'https://www.utv.ro/'],
  ['atomic-tv', 'Atomic TV', 'Muzică', 'https://atomictv.ro/'],
  ['kiss-tv', 'Kiss TV', 'Muzică', 'https://www.kisstv.ro/'],
  ['favorit-tv', 'Favorit TV', 'Muzică', 'https://favorittv.ro/'],
  ['etno-tv', 'Etno TV', 'Muzică', 'https://www.etno.ro/'],
  ['taraf-tv', 'Taraf TV', 'Muzică', 'https://www.taraf.tv/'],
  ['traditional-tv', 'Traditional TV', 'Muzică', 'https://traditionaltv.ro/'],
  ['tvr-folclor', 'TVR Folclor', 'Muzică', 'https://www.tvrplus.ro/'],
  ['mooz', 'Mooz', 'Muzică', 'https://mooz.tv/'],
  ['mooz-ro', 'Mooz RO', 'Muzică', 'https://mooz.tv/'],
  ['mooz-dance', 'Mooz Dance', 'Muzică', 'https://mooz.tv/'],
  ['mooz-hits', 'Mooz Hits', 'Muzică', 'https://mooz.tv/'],
  ['mooz-hd', 'Mooz HD', 'Muzică', 'https://mooz.tv/'],
  ['inedit-tv', 'Inedit TV', 'Muzică', 'https://inedittv.ro/'],
  ['emi-tv', 'EMI TV', 'Muzică', 'https://emitv.ro/'],
  ['balcan-music-tv', 'Balcan Music TV', 'Muzică', 'https://balcanmusic.tv/'],
  ['party-tv', 'Party TV', 'Muzică', 'https://partytv.ro/'],
  ['manele-tv', 'Manele TV', 'Muzică', 'https://maneletv.ro/'],
  ['hora-tv', 'Hora TV', 'Muzică', 'https://horatv.ro/'],
  ['bit-music', 'BIT Music', 'Muzică', 'https://bittv.info/'],

  // ---------- Copii ----------
  ['minimax', 'Minimax', 'Copii', 'https://www.minimax.ro/'],
  ['tvr-kids', 'TVR Kids', 'Copii', 'https://www.tvrplus.ro/'],
  ['boomerang-ro', 'Boomerang România', 'Copii', 'https://www.boomerangtv.ro/'],
  ['da-vinci-kids', 'Da Vinci Kids', 'Copii', 'https://davincikids.tv/'],

  // ---------- Cultură ----------
  ['tvr-cultural', 'TVR Cultural', 'Cultură', 'https://www.tvrplus.ro/'],
  ['cultural-tv', 'Cultural TV', 'Cultură', 'https://culturaltv.ro/'],

  // ---------- Religioase ----------
  ['trinitas-tv', 'Trinitas TV', 'Religioase', 'https://www.trinitas.tv/'],
  ['speranta-tv', 'Speranța TV', 'Religioase', 'https://www.sperantatv.ro/'],
  ['alfa-omega-tv', 'Alfa Omega TV', 'Religioase', 'https://alfaomega.tv/'],
  ['credo-tv', 'Credo TV', 'Religioase', 'https://credotv.ro/'],
  ['bethel-tv', 'Bethel TV', 'Religioase', 'https://betheltv.ro/'],
  ['armonia-tv', 'Armonia TV', 'Religioase', 'https://armoniatv.ro/'],
  ['nadejdea-tv', 'Nădejdea TV', 'Religioase', 'https://nadejdea.tv/'],

  // ---------- Tematice ----------
  ['agro-tv', 'Agro TV', 'Tematice', 'https://agro-tv.ro/'],
  ['agro-tv-moldova', 'Agro TV Moldova', 'Tematice', 'https://agrotvmoldova.md/'],
  ['medika-tv', 'Medika TV', 'Tematice', 'https://www.medikatv.ro/'],
  ['medical-tv', 'Medical TV', 'Tematice', 'https://medicaltv.ro/'],
  ['auto-motor-tv', 'Auto Motor și Sport TV', 'Tematice', 'https://automotorsport.ro/'],
  ['vanatoare-pescuit', 'Vânătoare și Pescuit', 'Tematice', 'https://vanatoaresipescuit.tv/'],
  ['imobiliare-tv', 'Imobiliare TV', 'Tematice', 'https://imobiliare.tv/'],

  // ---------- Regionale ----------
  ['bucuresti-tv', 'București TV', 'Regionale', 'https://bucurestitv.net/'],
  ['tele-europa-nova', 'Tele Europa Nova', 'Regionale', 'https://www.ten.ro/'],
  ['brasov-tv', 'Brașov TV', 'Regionale', 'https://brasovtv.com/'],
  ['nova-tv-brasov', 'Nova TV Brașov', 'Regionale', 'https://novatv.ro/'],
  ['mix-tv-brasov', 'Mix TV Brașov', 'Regionale', 'https://mixtv.ro/'],
  ['transilvania-live', 'Transilvania Live', 'Regionale', 'https://transilvanialive.ro/'],
  ['ncn-cluj', 'NCN Cluj', 'Regionale', 'https://ncn.ro/'],
  ['tv-cluj', 'TVR Cluj', 'Regionale', 'https://www.tvrplus.ro/'],
  ['alba-carolina-tv', 'Alba Carolina TV', 'Regionale', 'https://alba24.ro/'],
  ['info-hd', 'Info HD', 'Regionale', 'https://infohd.ro/'],
  ['moldova-tv', 'Moldova TV', 'Regionale', 'https://moldovatv.ro/'],
  ['iasi-tv-life', 'Iași TV Life', 'Regionale', 'https://www.iasitvlife.ro/'],
  ['tele-m-iasi', 'Tele M Iași', 'Regionale', 'https://telem.ro/'],
  ['tvr-iasi', 'TVR Iași', 'Regionale', 'https://www.tvrplus.ro/'],
  ['bit-tv', 'BIT TV', 'Regionale', 'https://bittv.info/'],
  ['telemoldova-plus', 'TeleMoldova Plus', 'Regionale', 'https://telemoldovaplus.ro/'],
  ['actualitatea-tv', 'Actualitatea TV', 'Regionale', 'https://actualitateatv.ro/'],
  ['tv-sud-est', 'TV Sud-Est', 'Regionale', 'https://tvsudest.ro/'],
  ['campus-tv', 'Campus TV', 'Regionale', 'https://campustv.ro/'],
  ['dobrogea-tv', 'Dobrogea TV', 'Regionale', 'https://dobrogea.tv/'],
  ['litoral-tv', 'Litoral TV', 'Regionale', 'https://litoraltv.ro/'],
  ['neptun-tv', 'Neptun TV', 'Regionale', 'https://neptuntv.ro/'],
  ['m9-tv', 'M9 TV', 'Regionale', 'https://m9tv.ro/'],
  ['tv-arad', 'TV Arad', 'Regionale', 'https://tvarad.ro/'],
  ['intermedia-tv', 'Intermedia TV', 'Regionale', 'https://intermediatv.ro/'],
  ['tvr-timisoara', 'TVR Timișoara', 'Regionale', 'https://www.tvrplus.ro/'],
  ['analog-tv-timisoara', 'Analog TV', 'Regionale', 'https://analogtv.ro/'],
  ['bucovina-tv', 'Bucovina TV', 'Regionale', 'https://bucovinatv.ro/'],
  ['suceava-live', 'Suceava Live', 'Regionale', 'https://suceavalive.ro/'],
  ['plus-tv-suceava', 'Plus TV Suceava', 'Regionale', 'https://plustv.ro/'],
  ['columna-tv', 'Columna TV', 'Regionale', 'https://columnatv.ro/'],
  ['valea-prahovei-tv', 'Valea Prahovei TV', 'Regionale', 'https://vp-tv.ro/'],
  ['accent-tv', 'Accent TV', 'Regionale', 'https://accenttv.ro/'],
  ['oltenia-tv', 'Oltenia TV', 'Regionale', 'https://olteniatv.ro/'],
  ['tele-2-drobeta', 'Tele 2 Drobeta', 'Regionale', 'https://tele2drobeta.ro/'],
  ['terra-sat-craiova', 'Terra Sat Craiova', 'Regionale', 'https://terrasat.ro/'],
  ['euro-tv-bacau', 'Euro TV Bacău', 'Regionale', 'https://eurotvbacau.ro/'],
  ['1-tv-bacau', '1 TV Bacău', 'Regionale', 'https://1tvbacau.ro/'],
  ['maramures-tv', 'Maramureș TV', 'Regionale', 'https://maramurestv.ro/'],
  ['nord-vest-tv', 'Nord Vest TV', 'Regionale', 'https://nordvesttv.ro/'],
  ['informatia-tv', 'Informația TV', 'Regionale', 'https://informatiatv.ro/'],
  ['satu-mare-tv', 'Satu Mare TV', 'Regionale', 'https://satumaretv.ro/'],
  ['tvs-sibiu', 'TVS Sibiu', 'Regionale', 'https://tvs.ro/'],
  ['ardeal-tv', 'Ardeal TV', 'Regionale', 'https://ardealtv.ro/'],
  ['tvr-craiova', 'TVR Craiova', 'Regionale', 'https://www.tvrplus.ro/'],
  ['tvr-tirgu-mures', 'TVR Târgu Mureș', 'Regionale', 'https://www.tvrplus.ro/'],
  ['star-tv-mures', 'Star TV Mureș', 'Regionale', 'https://startv.ro/'],
  ['ttm-tv', 'TTM Târgu Mureș', 'Regionale', 'https://ttm.ro/'],
  ['galati-tv', 'Galați TV', 'Regionale', 'https://galatitv.ro/'],
  ['tv-galati', 'TV Galați', 'Regionale', 'https://tvgalati.ro/'],
  ['vox-tv-braila', 'Vox TV Brăila', 'Regionale', 'https://voxtv.ro/'],
  ['arges-tv', 'Argeș TV', 'Regionale', 'https://argestv.ro/'],
  ['antena-1-pitesti', 'Absolut TV Pitești', 'Regionale', 'https://absoluttv.ro/'],
  ['tv-buzau', 'TV Buzău', 'Regionale', 'https://tvbuzau.ro/'],
  ['focus-tv-focsani', 'Focus TV Focșani', 'Regionale', 'https://focustv.ro/'],
  ['atlas-tv-slobozia', 'Atlas TV Slobozia', 'Regionale', 'https://atlastv.ro/'],
  ['tv-h-hunedoara', 'TV H Hunedoara', 'Regionale', 'https://tvh.ro/'],
  ['digi-24-oradea', 'Digi 24 Oradea', 'Regionale', 'https://www.digi24.ro/'],
  ['transilvania-tv-oradea', 'Transilvania TV Oradea', 'Regionale', 'https://transilvaniatv.ro/'],
  ['ram-tv-resita', 'RAM TV Reșița', 'Regionale', 'https://ramtv.ro/'],
  ['banat-tv', 'Banat TV', 'Regionale', 'https://banattv.ro/'],
  ['tv-deva', 'TV Deva', 'Regionale', 'https://tvdeva.ro/'],
  ['somes-tv', 'Someș TV', 'Regionale', 'https://somestv.ro/'],
  ['tv-zalau', 'TV Zalău', 'Regionale', 'https://tvzalau.ro/'],
  ['botosani-tv', 'Botoșani TV', 'Regionale', 'https://botosanitv.ro/'],
  ['tv-vaslui', 'TV Vaslui', 'Regionale', 'https://tvvaslui.ro/'],
  ['tele-neamt', 'Tele Neamț', 'Regionale', 'https://teleneamt.ro/'],
  ['tv-piatra-neamt', 'TV Piatra Neamț', 'Regionale', 'https://tvpn.ro/'],
  ['tv-giurgiu', 'TV Giurgiu', 'Regionale', 'https://tvgiurgiu.ro/'],
  ['tv-teleorman', 'TV Teleorman', 'Regionale', 'https://tvteleorman.ro/'],
  ['tv-calarasi', 'TV Călărași', 'Regionale', 'https://tvcalarasi.ro/'],
  ['tv-targoviste', 'TV Târgoviște', 'Regionale', 'https://tvtargoviste.ro/'],
  ['valcea-tv', 'Vâlcea TV', 'Regionale', 'https://valceatv.ro/'],
  ['gorj-tv', 'Gorj TV', 'Regionale', 'https://gorjtv.ro/'],
  ['tv-slatina', 'TV Slatina', 'Regionale', 'https://tvslatina.ro/'],
  ['tv-covasna', 'TV Covasna', 'Regionale', 'https://tvcovasna.ro/'],
  ['harghita-tv', 'Harghita TV', 'Regionale', 'https://harghitatv.ro/'],
  ['tv-bistrita', 'TV Bistrița', 'Regionale', 'https://tvbistrita.ro/'],
  ['alba-tv', 'Alba TV', 'Regionale', 'https://albatv.ro/'],
  ['tv-tulcea', 'TV Tulcea', 'Regionale', 'https://tvtulcea.ro/'],
  ['delta-tv', 'Delta TV', 'Regionale', 'https://deltatv.ro/'],
  ['tv-ialomita', 'TV Ialomița', 'Regionale', 'https://tvialomita.ro/'],
  ['ploiesti-tv', 'Ploiești TV', 'Regionale', 'https://ploiestitv.ro/']
];

// Culorile de accent pe categorie, folosite de generatorul de postere.
const CATEGORY_STYLE = {
  'Generaliste':  { from: '#1b4a8f', to: '#0a1f3d', accent: '#f5c451' },
  'Știri':        { from: '#8f2318', to: '#2b0b07', accent: '#ffb648' },
  'Sport':        { from: '#0f6b34', to: '#042113', accent: '#8ef2a4' },
  'Filme':        { from: '#5a2080', to: '#1a0a26', accent: '#e2a9ff' },
  'Divertisment': { from: '#a85a12', to: '#2e1705', accent: '#ffd58a' },
  'Documentare':  { from: '#155e75', to: '#062028', accent: '#7fe3f5' },
  'Lifestyle':    { from: '#9c2f6b', to: '#2c0a1e', accent: '#ffa8d4' },
  'Muzică':       { from: '#7a1f4d', to: '#230716', accent: '#ff9ec4' },
  'Copii':        { from: '#1f7a8c', to: '#08222a', accent: '#9ce8f2' },
  'Cultură':      { from: '#4a3a86', to: '#150f2b', accent: '#c0b3ff' },
  'Religioase':   { from: '#7a5b21', to: '#241a09', accent: '#ffe1a1' },
  'Tematice':     { from: '#2f6b5f', to: '#0b211d', accent: '#93e6d5' },
  'Regionale':    { from: '#26456b', to: '#0a1522', accent: '#9dc7f5' }
};

// Ordinea in care apar rubricile pe genuri in Stremio.
const CATEGORY_ORDER = [
  'Generaliste', 'Știri', 'Sport', 'Filme', 'Divertisment', 'Documentare',
  'Lifestyle', 'Muzică', 'Copii', 'Cultură', 'Religioase', 'Tematice', 'Regionale'
];

module.exports = { CATALOG, CATEGORY_STYLE, CATEGORY_ORDER };
