services:
  - type: web
    name: raultv-stremio
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /manifest.json
    envVars:
      - key: NODE_VERSION
        value: 20
